wandr/urls.py
from django.conf.urls import url
from wandr import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^picture_overview/$', views.picture_overview, name='picture_overview'),

    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^add_picture/$', views.add_picture, name='add_picture'),
    url(r'^add_picture_success/$', views.add_picture_success, name='add_picture_success'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.user_profile_view, name='user_profile'),
    url(r'^profile/(?P<user_id>[0-9]+)/upload_profile_picture/$', views.upload_profile_picture, name='upload_p_picture'),
    url(r'^profile/(?P<user_id>[0-9]+)/upload_cover_photo/$', views.upload_cover_photo, name='upload_cover_photo'),
    url(r'^profile/(?P<user_id>[0-9]+)/update_profile/$', views.update_profile, name='update_profile'),
    url(r'^profile/(?P<user_id>[0-9]+)/add/(?P<picture_id>[0-9]+)$', views.add_to_tgl, name='add_to_tgl'),
    url(r'^profile/(?P<user_id>[0-9]+)/remove_tgl/(?P<picture_id>[0-9]+)$', views.remove_from_tgl, name='remove_from_tgl'),
    url(r'^profile/(?P<user_id>[0-9]+)/remove_hbl/(?P<picture_id>[0-9]+)$', views.remove_from_hbl, name='remove_from_hbl'),

    url(r'^profile/(?P<user_id>[0-9]+)/like_picture/(?P<picture_id>[0-9]+)$', views.like_picture, name='like_picture'),
    url(r'^sitemap/$', views.sitemap, name='sitemap'),
]

wandr_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from wandr import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^wandr/', include('wandr.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wandr/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class HaveBeenList(models.Model):
    belongs_to = models.OneToOneField(User)

    total_likes = models.IntegerField(default=0)


    def __unicode__(self):
        return str(self.pk)


def create_hbl(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
        have_been_list = HaveBeenList.objects.create(belongs_to=kwargs['instance'])
        to_go_list = ToGoList.objects.create(belongs_to=kwargs['instance'])

post_save.connect(create_hbl, sender=User)


class ToGoList(models.Model):
    belongs_to = models.OneToOneField(User)

    def __unicode__(self):
        return str(self.pk)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    # additional attributes
    picture = models.ImageField(upload_to='profile_images', blank=True)
    cover_photo = models.ImageField(upload_to='cover_photos', blank=True)
    bio = models.TextField(max_length=50, blank=True)

    home_town = models.TextField(max_length=50, blank = True, default = '')
    tags = models.TextField(max_length=50, blank = True, default = '')

    def __unicode__(self):
        return str(self.user.username)


class Picture(models.Model):
    picture_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, unique=False)
    description = models.CharField(max_length=200, unique=False, default = 'unknown')
    picture = models.ImageField(upload_to='travel_images', blank=False)
    likes = models.IntegerField(default=0)
    have_been_list = models.ForeignKey(HaveBeenList, on_delete=models.CASCADE)
    to_go_list = models.ManyToManyField(ToGoList)
    location = models.CharField(max_length=128, unique=False)

    def __unicode__(self):
        return 'Name: ' + str(self.picture_id) + ' --- ID: ' + str(self.picture_id)

wandr/forms.py
from django import forms
from django.contrib.auth.models import User
from wandr.models import UserProfile, Picture

# Registration
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

# From to upload Profile Picture
class ProfilePictureForm(forms.ModelForm):
    picture = forms.ImageField(required=False, help_text="Upload your profile photo.")

    class Meta:
        model = UserProfile
        fields = ('picture',)

# Form to upload Cover Photo
class CoverPhotoForm(forms.ModelForm):
    cover_photo = forms.ImageField(required=False, help_text="Upload your Cover photo.")

    class Meta:
        model = UserProfile
        fields = ('cover_photo',)

# Form to upload Pictures
class PictureForm(forms.ModelForm):
    name = forms.CharField(max_length=128, required=True, help_text="Name your picture.")
    description = forms.CharField(max_length=200, required=True, help_text="Describe your picture in a short sentence")
    location = forms.CharField(max_length=128, required=True, help_text="Where did you take this picture?")
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    picture = forms.ImageField(required=True)

    class Meta:
        model = Picture
        fields = ('name', 'description', 'picture', 'location')

# contact form might be used in a later version, so it's not deleted
class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    form_content = forms.CharField(required=True, widget=forms.Textarea)

# Form for editing profile information
class BioForm(forms.ModelForm):
    bio = forms.CharField(required=False, widget=forms.Textarea, help_text="Tell the community about yourself.")
    home_town = forms.CharField(required=False, widget=forms.Textarea, help_text="Home town")
    tags = forms.CharField(required=False, widget=forms.Textarea, help_text="")

    class Meta:
        model = UserProfile
        fields = ('bio', 'home_town', 'tags')

wandr/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from .forms import ContactForm
from wandr.forms import UserForm, ProfilePictureForm, PictureForm, CoverPhotoForm, BioForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
#from registration.backends.simple.views import RegistrationView
from .models import User, HaveBeenList, Picture, UserProfile, ToGoList

# needed for the contact form email setup
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template


def index(request):
    picture_list = Picture.objects.order_by('-likes')[:6]
    user_id = request.user.pk
    hbl = HaveBeenList.objects.order_by('-total_likes')[:10]

    context_dict = {'pictures': picture_list, 'user_id': user_id, 'user_ranking': hbl,}

    return render(request, 'wandr/index.html', context=context_dict)


# register view added by Cristina 28.02.
def register(request):
    registered = False

    # If it's a HTTP POST, process form data
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            registered = True
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)

            if user:
            # If account is valid and active
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors)

    # Not a HTTP POST request so input is blank
    else:
        user_form = UserForm()

    return render(request, 'wandr/register.html',
                  {'user_form': user_form, 'registered': registered})


def picture_overview(request):
    picture_list = Picture.objects.order_by('-likes')
    context_dict = {'pictures': picture_list, }
    return render(request, 'wandr/picture_overview.html', context=context_dict)

# Created 01.03
def user_login(request):
    # If POST
    if request.method == 'POST':
        # Get username and password
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            # If account is valid and active
            if user.is_active:
                login(request, user)
                # return user to homepage
                return HttpResponseRedirect(reverse('index'))
            else:
                # Account is inactive
                return HttpResponse("Your Wandr account is disabled.")
        else:
            # Wrong details used
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    # If not POST
    else:
        return render(request, 'wandr/login.html', {})


@login_required
def add_to_tgl(request, user_id, picture_id):
    this_user = request.user
    tgl = ToGoList.objects.get(belongs_to=this_user)
    hbl_user = User.objects.get(pk=user_id)
    hbl = HaveBeenList.objects.get(belongs_to=hbl_user)

    print 'tgl id is ' + str(tgl.pk)
    picture = Picture.objects.get(pk=picture_id)
    picture.to_go_list.add(tgl)
    picture.save()
    tgl.save()

    print 'picture id is ' + str(picture_id)

    return HttpResponseRedirect(reverse('user_profile', args=[user_id]))


@login_required
def remove_from_tgl(request, user_id, picture_id):
    this_user = request.user
    tgl = ToGoList.objects.get(belongs_to=this_user)
    hbl_user = User.objects.get(pk=user_id)
    hbl = HaveBeenList.objects.get(belongs_to=hbl_user)

    print 'tgl id is ' + str(tgl.pk)
    picture = Picture.objects.get(pk=picture_id)
    picture.to_go_list.remove(tgl)
    picture.save()
    tgl.save()

    print 'picture id is ' + str(picture_id)

    return HttpResponseRedirect(reverse('user_profile', args=[user_id]))


@login_required
def remove_from_hbl(request, user_id, picture_id):
    this_user = request.user
    # tgl = ToGoList.objects.get(belongs_to=this_user)
    hbl_user = User.objects.get(pk=user_id)
    hbl = HaveBeenList.objects.get(belongs_to=hbl_user)

    picture = Picture.objects.get(pk=picture_id)
    picture.delete()

    print 'picture id is ' + str(picture_id)

    return HttpResponseRedirect(reverse('user_profile', args=[user_id]))


@login_required
# def upload_profile_picture(request, user_id):
def upload_profile_picture(request, user_id):
    # user_profile = UserProfile.objects.get(user=request.user)
    # uploaded = False
    # form = ProfilePictureForm(initial={'picture':user_profile.picture})

    if request.method == 'POST':
        user = request.user
        profile = UserProfile.objects.get(user=user)
        form = ProfilePictureForm(data=request.POST, instance=profile)

        # def get_object(self, queryset=None):
        #     return UserProfile.objects.get(user=self.request.user)

        if form.is_valid():
            page = form.save(commit=False)
            if 'picture' in request.FILES:
                page.picture = request.FILES['picture']
            # user = request.user
            # profile = UserProfile.objects.get(user=user)
            # profile.picture = page.picture
            # profile.picture = page.cleaned_data['picture']
            # picture = form.cleaned_data['picture']
            # profile.picture = picture
            profile.save()

            return HttpResponseRedirect(reverse('user_profile', args=[user_id]))

        else:
            print(form.errors)

        uploaded = True

    else:
        user = request.user
        profile = UserProfile.objects.get(user=user)
        form = ProfilePictureForm(instance=profile)

    return render(request, 'wandr/upload_profile_picture.html',
                  {'profile_picture_form': form, 'user_id': user_id})


@login_required
def like_picture(request, user_id, picture_id):
    if request.method == 'GET':
        if picture_id:
            pic = Picture.objects.get(picture_id=int(picture_id))
            if pic:
                likes = pic.likes + 1
                pic.likes = likes
                # 
                pic.have_been_list.total_likes = pic.have_been_list.total_likes + 1
                #
                pic.have_been_list.save()
                pic.save()
    return HttpResponseRedirect(reverse('user_profile', args=[user_id]))


@login_required
def upload_cover_photo(request, user_id):
    if request.method == 'POST':
        user = request.user
        profile = UserProfile.objects.get(user=user)
        form = CoverPhotoForm(data=request.POST, instance=profile)

        if form.is_valid():
            page = form.save(commit=False)
            if 'cover_photo' in request.FILES:
                page.cover_photo = request.FILES['cover_photo']

            profile.save()

            return HttpResponseRedirect(reverse('user_profile', args=[user_id]))

        else:
            print(form.errors)

    else:
        user = request.user
        profile = UserProfile.objects.get(user=user)
        form = CoverPhotoForm(instance=profile)

    return render(request, 'wandr/upload_cover_photo.html',
                  {'cover_photo_form': form, 'user_id': user_id})


# Created 01.03
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


# Created 02.03. Cristina
def about(request):
    return render(request, 'wandr/about.html')

def sitemap(request):
    return render(request, 'wandr/sitemap.html')


# created 08.03. Cynthia; email does not get sent
def contact(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the 
            # contact information
            template = get_template('wandr/contact_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Wandr" +'',
                ['2275765L@student.gla.ac.uk'],
                headers = {'Reply-To': contact_email }
            )
            email.send(fail_silently=False)
            return redirect('contact')

    return render(request, 'wandr/contact.html', {
        'form': form_class,
    })

# created 02.03. Cynthia

def add_picture_success(request):
	return render(request, 'wandr/add_picture_success.html')

@login_required
def add_picture(request):
	# form = PictureForm()

	# if request.method == 'POST':
	# 	form = PictureForm(request.POST)

	# 	if form.is_valid():
	# 		form.save(commit = True)
	# 		return index(request)
	# 	else:
	# 		print(form.errors)
	# return render(request, 'wandr/add_picture.html', {'form' : form})

    if request.method == 'POST':
        picture_form = PictureForm(request.POST, request.FILES)
        user_id = request.user.pk

        if picture_form.is_valid():
            picture = picture_form.save(commit=False)
            picture.have_been_list = HaveBeenList.objects.get(belongs_to=user_id)
            picture.save()

templates/wandr/about.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}
{% block title_block %}
	About us
{% endblock %}

{% block body_block %}
<div class="margin-control">
	<div class="about-block">
	<h1>About Wandr</h1>
	<p class="justified">
		This page is dedicated to all the romantic, curious and thrill-seeking adventurers out there! With Wandr, we provide a platform that allows you to share your best holiday snaps with like-minded globetrotters. Our mission is to let the community inspire each other and trigger a chain reaction that promotes wandrlust. We help people around the world to connect and inspirie each other by sharing their dream destinations.
    </p>
        <br/>
	</div>

    <div class="about-block">
    <h3>The Team</h3>
    <p>This web application was created by the team pinniped as part of the course Internet Technology at the University of Glasgow.</p>
        <div style="text-align: center"><img class="rounded mx-auto d-block" src="https://images7.alphacoders.com/326/thumb-1920-326765.jpg" alt="Team Pinniped" style="width:100%;"></div>
    <p style="text-align: center">Team: Cynthia, Robert, Cristina (who is who??)
    </p>
        <br/>
    </div>

    <div class="about-block">
        <p class="justified">Did you know that pinnipeds travel up to 21,000 km a year? We at Wandr don't make it quite that far. However, we are trying to keep up!
        The Wandr team consists of Cristina, Cynthia and Rob - Three master students at the Unverstiy of Glasgow School of Computing. If we are not busy tring to hack together a web application such as this, we like to spend our time with... you caught us there. We don't have hobbies.
        </p>
        <br/>
    </div>

    <div class="about-block">
        <h3>Contact us</h3>
        <p>Any questions or comments that you want to share? - Just leave us a message!
        </p>
        <p>
        <a href="mailto:2275765L@student.gla.ac.uk?Subject=Hello,%20Wandr%20Team" target="_top">2275765L@student.gla.ac.uk</a>
        </p>
    </div>
</div>
{% endblock %}

templates/wandr/add_picture.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add a Picture
{% endblock %}

{% block body_block %}

<div class="margin-control">
 <h1>
 Add a Picture
 </h1>
 <div>

 <div class="container col-sm-10">
	<form id="picture_form" method="post" action="/wandr/add_picture/" enctype="multipart/form-data" >
		{% csrf_token %}

		<!-- {{ picture_form.as_p }} -->

		{% for hidden in picture_form.hidden_fields %}
			{{ hidden }}
		{% endfor %}

		{% for field in picture_form.visible_fields %}

			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-form-label col-sm-2">
           				{{ field.label }}
         		</label>
         		<div class="col-sm-10">
         		<!-- {{ field }} -->
         		<input id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" class="form-control" placeholder="{{ field.help_text }}">
         		</div>
			</div>
		{% endfor %}

		<!-- Error messaging -->
        {% if picture_form.errors %}
        <div class="alert alert-warning" role="alert">
            <div class="inner">
                <p>There were some errors in the information you entered. Please correct the following:</p>
                {{ picture_form.non_field_errors }}
                    {% for field in picture_form %}
                        {% if field.errors %}
                            <li>
                                {{ field.label }}:
                                {{ field.errors|striptags }}
                            </li>
                        {% endif %}
                    {% endfor %}
            </div>
        </div>

        {% endif %}
        <!-- /Error messaging -->

		<input class="btn btn-primary" type="submit" name ="submit" value = "Upload Picture"" />
	</form>
</div>
 </div>
 </div>
{% endblock %}

templates/wandr/add_picture_success.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	You've successfully added a picture!
{% endblock %}

{% block body_block %}
	<div class="margin-control">
		<h1>
			You've successfully added a picture!
		</h1>
	</div>
{% endblock %}

templates/wandr/contact.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}
{% block title_block %}
	Contact
{% endblock %}

{% block body_block %}
<div class="margin-control">
    <h1>Contact Us</h1>
    <div>
        <h2>Any questions or comments that you want to share?
        </h2>
        <h2>
        <a href="mailto:2275765L@student.gla.ac.uk?Subject=Hello,%20Wandr%20Team" target="_top">2275765L@student.gla.ac.uk</a>
        </h2>
    </div>
</div>
{% endblock %}

templates/wandr/login.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<div class="margin-control">
    <h1>Login to Wandr</h1>
        <form id="login_form" method="post" action="{% url 'login' %}">
            {% csrf_token %}

            <div class="form-group container col-sm-10">
            <input type="text" class="form-control"  name="username" value="" placeholder="Username" size="50" />
            </div>
            <div class="form-group container col-sm-10">
            <input type="password" class="form-control" name="password" value="" placeholder="Password" size="50" />
            </div>
            <div class="container col-sm-10">
            <input type="submit" class="btn btn-primary" value="submit" />
            </div>
        </form>
</div>
{% endblock %}

templates/wandr/register.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}

{% block css_block %}
    <link rel="stylesheet" href="{% static "css/form.css" %}" />
{% endblock %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<div class="margin-control">
    <h1>Register for Wandr</h1>

    {% if registered %}
        Thanks for registering!
    {% else %}

    <!-- This displays the form components -->
    <div class="container col-sm-10">
        <form id="user_form" method="post" action="{% url 'register' %}" enctype="multipart/form-data">
        {% csrf_token %}
            {% for field in user_form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-form-label col-sm-2">
                        {{ field.label }}
                    </label>
                    <div class="col-sm-10">
                        <!-- {{ field }} -->
                        <input id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" class="form-control" placeholder="{{ field.help_text }}">
                    </div>
                </div>
            {% endfor %}
            
        
        <!-- Error messaging -->
        {% if user_form.errors %}
        <div class="alert alert-warning" role="alert">
            <div class="inner">
                <p>There were some errors in the information you entered. Please correct the following:</p>
                {{ user_form.non_field_errors }}
                    {% for field in user_form %}
                        {% if field.errors %}
                            <li>
                                {{ field.label }}: {{ field.errors|striptags }}
                            </li>
                        {% endif %}
                    {% endfor %}
            </div>
        </div>
        {% endif %}
        <!-- /Error messaging -->

        <input type="submit" class="btn btn-primary" name="submit" value="Register" />

        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/wandr/sitemap.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}
{% block title_block %}
	Sitemap
{% endblock %}

{% block body_block %}
<br/>
<h1>Sitemap</h1>
<!-- only for loged out pages -->
<div class="about-block">
<a href="{% url 'about' %}">About</a><br/>
<a href="{% url 'login' %}">Login</a><br/>
<a href="{% url 'register' %}">Sign Up</a></br>
</div>

{% endblock %}

templates/wandr/user_profile.html
{% extends 'wandr/base.html' %}
{% load staticfiles %}

{% block css_block %}
    <link rel="stylesheet" href="{% static "css/style.css" %}" />

{% endblock %}

{% block title_block %}
    User {{ user.username }}
{% endblock %}

{% block body_block %}

    <!-- Cover photo -->
    <div id="cover-photo-container">
        {% if user.userprofile.cover_photo %}
            {% if this_user %}
                <div class="edit-cover-photo-icon"><a href="{% url 'upload_cover_photo' user.id %}"><img src="../../../static/images/edit_pencil.jpg"></a></div>
            {% endif %}
            <div id="cover-photo-wrapper" style="background:url('/media/{{ user.userprofile.cover_photo }}');"></div>
        {% else %}
            {% if this_user %}
                <a href="{% url 'upload_cover_photo' user.id %}">
                    <div id="empty-cover-photo-wrapper">
                        <h1>Upload your cover photo</h1><img src="../../../static/images/plus.png" alt="">
                    </div>
                </a>
            {% endif %}
        {% endif %}
    </div>

    <!-- Profile Picture -->
    <div id="profile-picture-container">
        {% if user.userprofile.picture %}
            <div id="profile-picture-wrapper">
                {% if this_user %}
                    <div class="edit-profile-pic-icon">
                        <a href="{% url 'upload_p_picture' user.id %}">
                            <img class="edit-pencil-img" src="../../../static/images/edit_pencil.jpg" />
                        </a>
                    </div>
                {% endif %}
                    <img class="profile-picture-img" src="/media/{{ user.userprofile.picture }}" alt="profile_image">
            </div>
        {% else %}
            <div id="empty-profile-picture-wrapper">
                {% if this_user %}
                    <a href="{% url 'upload_p_picture' user.id %}">
                        <img src="{% static '/images/add-profile-picture.jpg' %}" alt="profile_image">
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <div>
    {% if this_user %}
        <h1>{{ user.username }}</h1>
    {% else %}
        <h1>{{ user.username }} </h1>
    {% endif %}
    </div>

    <div id="user-info-container" class="container-fluid">
        <div class="col-md-12">
            <!-- User Bio -->
            <div class="col-md-4">

            {% if this_user %}
                <h2>About You<a href="{% url 'update_profile' user.id %}"><img class="edit-pencil-img" src="{% static '/images/edit_pencil.jpg' %}" /></a></h2>
            {% else %}
                <h2>{{ user.username }}'s Bio</h2>
            {% endif %}    
                <p class="text-justify">{{ user.userprofile.bio }}</p>
            </div>

            <!-- User Info -->
            <div class="col-md-4 col-md-push-4">
                <h2>User Info</h2>
                <div class="col-md-12">
                    <h4> 
                        <div class="col-md-3">
                            <span class="glyphicon glyphicon-home"></span>
                        </div>
                        <div class="col-md-9">
                            {{ user.userprofile.home_town }} 
                        </div>
                    </h4>
                </div>
                <div class="col-md-12">
                    <h4>    
                        <div class="col-md-3">
                            <span class="glyphicon glyphicon-tags"></span>
                        </div>
                        <div class="col-md-9">
                            {{ user.userprofile.tags }}
                        </div>
                    </h4>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">
        <!-- Have Been List -->
        <div class="hbl-container col-md-6">
            <div class="hbl-title-container">
            {% if this_user %}
                <h2>Have Been List</h2>

                <a href="{% url 'add_picture' %}">
                    <div class="hbl-add-picture-button">
                        <img src="{% static '/images/plus.png' %}" alt="add picture">
                    </div>
                </a>

            {% else %}
                <h2>{{ user.username }}'s Have Been List</h2>
            {% endif %}

            </div>

            {% for picture in hbl.picture_set.all %}
                <div class="list-img-container col-md-6">
                <!-- If logged in user they can delete hbl photos -->
                    {% if this_user %}
                    <div class="add-to-tgl">
                        <a href="{% url 'remove_from_hbl' user.id picture.pk %}">
                            <img src="{% static '/images/delete.png' %}">
                        </a>
                    </div>
                    {% else %}
                    <!-- If logged in user is on their own profile don't allow to add pictures to tgl -->
                    <div class="add-to-tgl">
                        <a href="{% url 'add_to_tgl' user.id picture.pk %}">
                            <img src="{% static '/images/plus.png' %}">
                        </a>
                    </div>

                    <!-- likes -->
                    <div class="like-picture">
                        <a href="{% url 'like_picture' user.id picture.pk %}">
                            <img src="{% static '/images/heart.png' %}">
                            <div class="like-count">
                                {{ picture.likes }}
                            </div>
                        </a>
                    </div>

                    {% endif %}
                    <img class="profile-list-image" src="/media/{{ picture.picture }}" alt="{{ picture.name }}">
                </div>
            {% endfor %}

        </div>


        <!-- To Go List -->
        <div class="tgl-container col-md-6">
            <h2>To Go List</h2>
            {% for picture in tgl.picture_set.all %}
                <div class="list-img-container col-md-6">
                    {% if this_user %}
                    <div class="add-to-tgl">
                        <a href="{% url 'remove_from_tgl' user.id picture.pk %}">
                            <img src="{% static '/images/delete.png' %}">
                        </a>
                    </div>
    <!-- cynthias changes start -->
                    {% else %}

                    <div class="add-to-tgl">
                        <a href="{% url 'add_to_tgl' user.id picture.pk %}">
                            <img src="{% static '/images/plus.png' %}">
                        </a>
                    </div>

                    <div class="like-picture">
                        <a href="{% url 'like_picture' user.id picture.pk %}">
                            <img src="{% static '/images/heart.png' %}">
                            <div class="like-count">
                                {{ picture.likes }}
                            </div>
                        </a>
                    </div>
    <!-- changes end -->


                    {% endif %}
                    <img class="profile-list-image" src="/media/{{ picture.picture }}" alt="{{ picture.name }}">
                </div>


            {% endfor %}

        </div>
    </div>


{% endblock %}